[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true
extend-exclude = "venv/|.venv/|alembic/|docker/|__pycache__/|.git/"

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 120
extend-ignore = ""
exclude = ".git,__pycache__,venv,.venv,alembic,docker"