# APP_HOST=localhost
# APP_PORT=8000
# PATH_PREFIX=/api/v1

# ACCESS_TOKEN_SECRET_KEY=1Dg4zlMWZ/Ide5M1NBAGBx+y+8uRW91F7pR7FFoAIqI=
# ACCESS_TOKEN_ALGORITHM=HS256
# ACCESS_TOKEN_EXPIRE_MINUTES=15

# INTERNAL_ADMIN_USERNAME=admin
# INTERNAL_ADMIN_PASSWORD=admin123

# RELOAD_APP=True

# ENV=test
